# Generated by Django 3.0.8 on 2020-07-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_Organisation',
            field=models.BooleanField(default=False),
        ),
    ]
